"""Add online_mode column

Revision ID: 0bae0007b159
Revises: 974e10781089
Create Date: 2026-04-06 23:14:27.696946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bae0007b159'
down_revision: Union[str, Sequence[str], None] = '974e10781089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miniverses', sa.Column('online_mode', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miniverses', 'online_mode')
    # ### end Alembic commands ###
