"""Adding java_version

Revision ID: 974e10781089
Revises: a35a7fd95c00
Create Date: 2026-03-28 17:27:28.437335

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '974e10781089'
down_revision: Union[str, Sequence[str], None] = 'a35a7fd95c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miniverses', sa.Column('java_version', sa.String(length=64), nullable=True))
    op.alter_column('miniverses', 'allow_bedrock',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=False,
                    existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('miniverses', 'allow_bedrock',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=True,
                    existing_server_default=sa.text("'0'"))
    op.drop_column('miniverses', 'java_version')
    # ### end Alembic commands ###
