"""Add allow_bedrock to Miniverse

Revision ID: a35a7fd95c00
Revises: a524f7b6c960
Create Date: 2026-03-15 19:42:19.942665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35a7fd95c00'
down_revision: Union[str, Sequence[str], None] = 'a524f7b6c960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miniverses', sa.Column('allow_bedrock', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miniverses', 'allow_bedrock')
    # ### end Alembic commands ###
