"""Initial migration

Revision ID: a524f7b6c960
Revises: 
Create Date: 2026-03-15 19:20:10.354942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a524f7b6c960'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miniverses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('VANILLA', 'PAPER', 'FABRIC', 'FORGE', 'NEO_FORGE', name='miniversetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('container_id', sa.String(length=64), nullable=True),
    sa.Column('mc_version', sa.String(length=64), nullable=False),
    sa.Column('subdomain', sa.String(length=128), nullable=False),
    sa.Column('is_on_lite_proxy', sa.Boolean(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('management_server_secret', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('NONE', 'USER', 'MODERATOR', 'ADMIN', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('miniverse_user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('miniverse_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('NONE', 'USER', 'MODERATOR', 'ADMIN', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['miniverse_id'], ['miniverses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'miniverse_id')
    )
    op.create_table('mods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('version_id', sa.String(length=16), nullable=True),
    sa.Column('project_id', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('version_name', sa.String(length=128), nullable=True),
    sa.Column('version_number', sa.String(length=128), nullable=True),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('miniverse_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['miniverse_id'], ['miniverses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mods')
    op.drop_table('miniverse_user_roles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_table('miniverses')
    # ### end Alembic commands ###
